# Levantar el ambiente: docker-compose up
# Para reiniciar todo el ambiente: en
# este comando es para cuando hay bugs de conexion docker-compose down -v
version: '3.3'
services:
  mariadb:
    container_name: mariadb_app
    image: mariadb
    restart: always
    environment:
      # Nombre de la base de datos
      MYSQL_DATABASE: 'jetesa_'
      # Usuario de la base de datos
      MYSQL_USER: 'jetesa_'
      # Password de la base de dato
      MYSQL_PASSWORD: 'jetesa_1234*'
      # Password del root
      MYSQL_ROOT_PASSWORD: 'jetesa_1234*'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '30721:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql

# Names our volume
volumes:
  mysql-volume:
